version: 1
disable_existing_loggers: False
formatters:
  custom:
    class: uvicorn.logging.ColourizedFormatter
    format: "%(levelprefix)s %(asctime)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: custom
    level: DEBUG
loggers:
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: no
  fastapi:
    level: DEBUG
    handlers: [console]
    propagate: no
  sqlalchemy.engine:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
